-- AULA 040
-- CRIANDO TESTE
CREATE TABLE Cadastro
(
Nome varchar(50) NOT NULL,
docto varchar(20) NOT NULL
)

-- INICIA A TRANSA플O
BEGIN TRANSACTION

-- INSERIR REGISTROS
INSERT INTO Cadastro VALUES ('KARLA','123456789')
INSERT INTO Cadastro VALUES ('WEVERTON','123789456')
INSERT INTO Cadastro VALUES ('NALVA','789456123')

-- CRIA UM PONTO DE RESTAURA플O
SAVE TRANSACTION a1

-- INSERIR NOVO REGISTRO
INSERT INTO Cadastro VALUES ('Carlos','951753654')

-- CRIAR OUTRO PONTO DE RESTAURA픈O
SAVE TRANSACTION a2

-- INSERIR NOVO REGISTRO 
INSERT INTO Cadastro VALUES ('Luiz','963852714')

-- CRIA OUTRO PONTO DE RESTAURA플O
SAVE TRANSACTION a3

-- SELECT DO REGISTRO
SELECT * FROM Cadastro

-- RETORNA A TABELA NO ESTADO ANTERIOR AO BEGIN TRANSACTION
ROLLBACK

-- RETORNA A TABELA AO PONTO DE RESTAURA플O A1, A2 OU A3
ROLLBACK TRANSACTION a1
ROLLBACK TRANSACTION a2
ROLLBACK TRANSACTION a3

-- EFETIVA AS INFORMA합ES DA TABELA NO BANCO DE DADOS
COMMIT TRANSACTION

DELETE FROM Cadastro