--AULA 050
--RANK: EXEMPLO 2:1
/*
 AS FUNÇÕES DE CLASSIFICAÇÃO RETORNAM UM VALOR DE CLASSIFICAÇÃO PARA CADA LINHA EM UMA PARTIÇÃO. DEPENDENDO DA FUNÇÃO USADA, 
ALGUMAS LINHAS PODEM RECEBER O MESMO VALOR QUE OUTRAS. AS FUNÇÕES DE CLASSIFICAÇÃO SÃO NÃO DETERMINISTICAS.
*/
SELECT RANK() OVER (ORDER BY Estado ASC) AS rank_uf ,
		estado
FROM uf

-- RANK EXEMPLO 2
SELECT RANK() OVER (ORDER BY Estado ASC) AS rank_uf,
	Regiao, 
	Estado
FROM regiao_uf

-- RANK EXEMPLO 3
SELECT RANK() OVER (ORDER BY Regiao ASC) AS rank_uf,
	Regiao,
	Estado
FROM regiao_uf

-- NTILE
/* 
DISTRIBUI AS LINHAS DE UMA PARTIÇÃO ORDENADA EM UM NÚMERO DE GRUPOS EPESCIFICADOS.
OS GRUPOS SÃO NUMERADOS, INICIALMENTE EM UM. PARA CADA LINHA, NTILE RETORNA O NÚMERO DO GRUPO AO QUAL A LINHA PERTENCE.
*/
SELECT NTILE(5) OVER (ORDER BY Regiao ASC) AS Ntile_uf,
	Regiao,
	Estado
FROM regiao_uf

-- AULA 051
/*
RETORNA A CLASSIFICAÇÃO DE LINHAS DENTRO DA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
SEM QUALQUER LACUNA NA CLASSIFICAÇÃO. A CLASSIFICAÇÃO DE UMA LINHA É UM MAIS O NÚMERO DE CLASSIFICAÇÕES DISTINTAS QUE VÊM ANTES DA LINHA EM QUESTÃO.
*/
SELECT DENSE_RANK() OVER (ORDER BY Regiao ASC) AS dense_rank_uf,
	Regiao,
	Estado
FROM Regiao_uf

SELECT DENSE_RANK() OVER (ORDER BY Estado ASC) AS DENSE_RANK_UF,
	regiao,
	estado
FROM regiao_uf

-- ROW_NUMBER
/* RETORNA O NÚMERO SEQUENCIAL DE UMA LINHA EM UMA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
INICIANDO EM 1 PARA A PRIMEIRA LINHA DE CADA PARTIÇÃO.
*/
SELECT ROW_NUMBER() OVER (ORDER BY Estado ASC) AS Row_Number_Uf,
	Regiao,
	estado
FROM regiao_uf

-- COMBINANDO VALORES 01
SELECT	ROW_NUMBER() OVER (ORDER BY Regiao ASC) AS ROW_NUMBER_UF,
		DENSE_RANK() OVER (ORDER BY Regiao ASC) AS DENSE_RANK_UF,
		NTILE(5) OVER (ORDER BY Regiao ASC) AS NTILE_UF,
		RANK() OVER (ORDER BY Regiao ASC) AS Rank_UF,
		Regiao,
		Estado
FROM regiao_uf
ORDER BY 5,6

-- SIMULAMDO CLASSIFICAÇÂO DE CAMPEONATO
-- DROPs TABLE CAMPEONATO
CREATE TABLE Campeonato
(
	Nometime	Varchar(30) NOT NULL,
	Pontos		INT NOT NULL	

	)

-- POPULANDO TABELA

insert into campeonato values ('Corinthians','53');
insert into campeonato values ('Grêmio','43');
insert into campeonato values ('Santos','41');
insert into campeonato values ('Palmeiras','40');
insert into campeonato values ('Flamengo','38');
insert into campeonato values ('Cruzeiro','37');
insert into campeonato values ('Botafogo','37');
insert into campeonato values ('Atlético-PR','34');


