--AULA 050
--RANK: EXEMPLO 2:1
/*
 AS FUNÇÕES DE CLASSIFICAÇÃO RETORNAM UM VALOR DE CLASSIFICAÇÃO PARA CADA LINHA EM UMA PARTIÇÃO. DEPENDENDO DA FUNÇÃO USADA, 
ALGUMAS LINHAS PODEM RECEBER O MESMO VALOR QUE OUTRAS. AS FUNÇÕES DE CLASSIFICAÇÃO SÃO NÃO DETERMINISTICAS.
*/
SELECT RANK() OVER (ORDER BY Estado ASC) AS rank_uf ,
		estado
FROM uf

-- RANK EXEMPLO 2
SELECT RANK() OVER (ORDER BY Estado ASC) AS rank_uf,
	Regiao, 
	Estado
FROM regiao_uf

-- RANK EXEMPLO 3
SELECT RANK() OVER (ORDER BY Regiao ASC) AS rank_uf,
	Regiao,
	Estado
FROM regiao_uf
